#!/bin/bash

echo "Install locale"
apt-get -o Acquire::ForceIPv4=true update --fix-missing
apt-get install -y tzdata locales
locale-gen $1
ln -fs /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
