#!/bin/bash

# Passed arguments
echo "arg1: $1 \ arg2: $2"
serversIP=$1
glusterVolumes=$2


# debug
# serversIP=",172.21.12.12,172.21.12.11"
# glusterVolumes="glusterfs-0,glusterfs-1"

OLDIFS=$IFS
IFS=','

# First Server (reversed)
read -ra ADDR <<< "$serversIP" # is read into an array as tokens separated by IFS
ADDR_LAST=${#ADDR[@]}-1
ip=${ADDR[$ADDR_LAST]}
echo "Client: Connected IP - $ip"

# First Volume
read -ra VOL <<< "$glusterVolumes" # is read into an array as tokens separated by IFS
volume=${VOL[0]}
echo "Client: Connected Volume - $volume"

sudo mkdir /mnt/glusterfs
sudo mount -t glusterfs $ip:/$volume /mnt/glusterfs

echo hello | sudo tee /mnt/glusterfs/testfile.txt

IFS=$OLDIFS
