#!/bin/bash

# Passed arguments
echo "arg1: $1 \ arg2: $2"
serversIP=$1
glusterVolumes=$2

sudo mkdir /mnt/glusterfs
sudo mount -t glusterfs 172.21.12.11:/$glusterVolumes /mnt/glusterfs

echo hello | sudo tee /mnt/glusterfs/testfile.txt
