# https://github.com/kubernetes/examples/tree/master/volumes/glusterfs
# Not finished!!
kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 172.21.12.11
  ports:
  - port: 24007
- addresses:
  - ip: 172.21.12.12
  ports:
  - port: 24007
- addresses:
  - ip: 172.21.12.13
  ports:
  - port: 24007
---
kind: Service
apiVersion: v1
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 24007
---
apiVersion: v1
kind: Pod
metadata:
  name: glusterfs
spec:
  containers:
  - name: glusterfs
    image: nginx
    volumeMounts:
    - mountPath: "/mnt/glusterfs"
      name: glusterfsvol
  volumes:
  - name: glusterfsvol
    glusterfs:
      endpoints: glusterfs-cluster
      path: kube_vol
      readOnly: true


